#!/bin/sh

echo "Executing /etc/qemu-ifup"
echo "Bringing up $1 for bridge mode ..."
echo sudo /sbin/ifconfig $1 192.168.1.12 up
sudo /sbin/ifconfig $1 192.168.1.12 up
echo $?
echo "Adding $1 to br0 ..."
sudo /usr/sbin/brctl addif br0 $1
echo $?
sleep 2
